title: "Camilo Pedraza Jiménez"
name: "Camilo Pedraza Jiménez"
description: "PhD researcher – [your field/department/university]"
url: "https://cpj97.github.io"
# Minimal Mistakes via remote theme (no local Ruby needed on GitHub)
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-include-cache

# Look & feel
minimal_mistakes_skin: default
locale: en
logo: /assets/img/tree.webp   # optional; add an image later
breadcrumbs: true
search: false

# Collections (optional later)
# collections:
#   posts:
#     output: true
#     permalink: /blog/:title/

include:
  - _pages

author:
  name: "Camilo Pedraza Jiménez"
  avatar: "/assets/img/yo_zoom.png"   # optional
  bio: |
    PhD researcher in Computational Social Science.
    
    **Interests:** Sustainable Development, Quantitative Research.
  location: "Berlin & Bogota"
  links:
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:C.Pedraza-Jimenez@phd.hertie-school.org"
    - label: "LinkedIn"
      icon: "fab fa-linkedin"
      url: "https://www.linkedin.com/in/camilo-pedraza-jim%C3%A9nez-67257a182/"
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/cpj97"


# Navigation (points to _data/navigation.yml)
